# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: execution.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'execution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65xecution.proto\x12\x0brqt2.api.v1\x1a\x0btypes.proto\"\xe2\x01\n\nRunRequest\x12\x0f\n\x07package\x18\x01 \x01(\t\x12\x12\n\nexecutable\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\x12\x10\n\x08ros_args\x18\x04 \x03(\t\x12-\n\x03\x65nv\x18\x05 \x03(\x0b\x32 .rqt2.api.v1.RunRequest.EnvEntry\x12\x0b\n\x03\x63wd\x18\x06 \x01(\t\x12\x12\n\nuse_launch\x18\x07 \x01(\x08\x12\x13\n\x0blaunch_file\x18\x08 \x01(\t\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"F\n\x0bStopRequest\x12\r\n\x03pid\x18\x01 \x01(\x05H\x00\x12\x13\n\tnode_name\x18\x02 \x01(\tH\x00\x12\r\n\x05\x66orce\x18\x03 \x01(\x08\x42\x04\n\x02\x65v\"s\n\tExecEvent\x12$\n\x03log\x18\x01 \x01(\x0b\x32\x15.rqt2.api.v1.LogEntryH\x00\x12%\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.StatusH\x00\x12\x13\n\texit_code\x18\x03 \x01(\x05H\x00\x42\x04\n\x02\x65v\"O\n\x12LaunchListResponse\x12\x14\n\x0claunch_files\x18\x01 \x03(\t\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.Status2\xcb\x01\n\x10\x45xecutionService\x12\x38\n\x03Run\x12\x17.rqt2.api.v1.RunRequest\x1a\x16.rqt2.api.v1.ExecEvent0\x01\x12\x35\n\x04Stop\x12\x18.rqt2.api.v1.StopRequest\x1a\x13.rqt2.api.v1.Status\x12\x46\n\x0fListLaunchFiles\x12\x12.rqt2.api.v1.Empty\x1a\x1f.rqt2.api.v1.LaunchListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'execution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNREQUEST_ENVENTRY']._loaded_options = None
  _globals['_RUNREQUEST_ENVENTRY']._serialized_options = b'8\001'
  _globals['_RUNREQUEST']._serialized_start=46
  _globals['_RUNREQUEST']._serialized_end=272
  _globals['_RUNREQUEST_ENVENTRY']._serialized_start=230
  _globals['_RUNREQUEST_ENVENTRY']._serialized_end=272
  _globals['_STOPREQUEST']._serialized_start=274
  _globals['_STOPREQUEST']._serialized_end=344
  _globals['_EXECEVENT']._serialized_start=346
  _globals['_EXECEVENT']._serialized_end=461
  _globals['_LAUNCHLISTRESPONSE']._serialized_start=463
  _globals['_LAUNCHLISTRESPONSE']._serialized_end=542
  _globals['_EXECUTIONSERVICE']._serialized_start=545
  _globals['_EXECUTIONSERVICE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
