# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: installer.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'installer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finstaller.proto\x12\x08rqt2_api\"\x10\n\x0eInstallRequest\"w\n\x0fInstallProgress\x12\x0f\n\x07step_id\x18\x01 \x01(\t\x12\x10\n\x08log_line\x18\x02 \x01(\t\x12$\n\x06status\x18\x03 \x01(\x0e\x32\x14.rqt2_api.StepStatus\x12\x1b\n\x13progress_percentage\x18\x04 \x01(\x05*2\n\nStepStatus\x12\x0b\n\x07RUNNING\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x32\x62\n\x13ROSInstallerService\x12K\n\x12InstallEnvironment\x12\x18.rqt2_api.InstallRequest\x1a\x19.rqt2_api.InstallProgress0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'installer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STEPSTATUS']._serialized_start=168
  _globals['_STEPSTATUS']._serialized_end=218
  _globals['_INSTALLREQUEST']._serialized_start=29
  _globals['_INSTALLREQUEST']._serialized_end=45
  _globals['_INSTALLPROGRESS']._serialized_start=47
  _globals['_INSTALLPROGRESS']._serialized_end=166
  _globals['_ROSINSTALLERSERVICE']._serialized_start=220
  _globals['_ROSINSTALLERSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
