# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: system_utils.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'system_utils.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12system_utils.proto\x12\x0brqt2.api.v1\x1a\x0btypes.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n\x0e\x43ommandRequest\x12\x12\n\nexecutable\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\x31\n\x03\x65nv\x18\x03 \x03(\x0b\x32$.rqt2.api.v1.CommandRequest.EnvEntry\x12\x13\n\x0bworking_dir\x18\x04 \x01(\t\x12\x11\n\tsudowoodo\x18\x05 \x01(\x08\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"u\n\rCommandOutput\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x06stream\x18\x02 \x01(\x0e\x32\x17.rqt2.api.v1.StreamType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"x\n\tSSHConfig\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x12\n\x08password\x18\x04 \x01(\tH\x00\x12\x12\n\x08key_path\x18\x05 \x01(\tH\x00\x12\x11\n\ttimeout_s\x18\x06 \x01(\x05\x42\x06\n\x04\x61uth\"a\n\nSSHSession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12#\n\x06status\x18\x04 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"F\n\x11RemoteExecRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t*$\n\nStreamType\x12\n\n\x06STDOUT\x10\x00\x12\n\n\x06STDERR\x10\x01\x32\xa0\x02\n\x0bSystemUtils\x12\x38\n\rRestartDaemon\x12\x12.rqt2.api.v1.Empty\x1a\x13.rqt2.api.v1.Status\x12G\n\nRunCommand\x12\x1b.rqt2.api.v1.CommandRequest\x1a\x1a.rqt2.api.v1.CommandOutput0\x01\x12\x42\n\x0fStartSSHSession\x12\x16.rqt2.api.v1.SSHConfig\x1a\x17.rqt2.api.v1.SSHSession\x12J\n\nExecRemote\x12\x1e.rqt2.api.v1.RemoteExecRequest\x1a\x1a.rqt2.api.v1.CommandOutput0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_utils_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST_ENVENTRY']._loaded_options = None
  _globals['_COMMANDREQUEST_ENVENTRY']._serialized_options = b'8\001'
  _globals['_STREAMTYPE']._serialized_start=681
  _globals['_STREAMTYPE']._serialized_end=717
  _globals['_COMMANDREQUEST']._serialized_start=82
  _globals['_COMMANDREQUEST']._serialized_end=267
  _globals['_COMMANDREQUEST_ENVENTRY']._serialized_start=225
  _globals['_COMMANDREQUEST_ENVENTRY']._serialized_end=267
  _globals['_COMMANDOUTPUT']._serialized_start=269
  _globals['_COMMANDOUTPUT']._serialized_end=386
  _globals['_SSHCONFIG']._serialized_start=388
  _globals['_SSHCONFIG']._serialized_end=508
  _globals['_SSHSESSION']._serialized_start=510
  _globals['_SSHSESSION']._serialized_end=607
  _globals['_REMOTEEXECREQUEST']._serialized_start=609
  _globals['_REMOTEEXECREQUEST']._serialized_end=679
  _globals['_SYSTEMUTILS']._serialized_start=720
  _globals['_SYSTEMUTILS']._serialized_end=1008
# @@protoc_insertion_point(module_scope)
