# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workspace.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'workspace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fworkspace.proto\x12\x0brqt2.api.v1\x1a\x0btypes.proto\"$\n\x14OpenWorkspaceRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"=\n\x0bPackageInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x12\n\nbuild_type\x18\x03 \x01(\t\"h\n\x15OpenWorkspaceResponse\x12*\n\x08packages\x18\x01 \x03(\x0b\x32\x18.rqt2.api.v1.PackageInfo\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"-\n\x13ListPackagesRequest\x12\x16\n\x0eworkspace_path\x18\x01 \x01(\t\"g\n\x14ListPackagesResponse\x12*\n\x08packages\x18\x01 \x03(\x0b\x32\x18.rqt2.api.v1.PackageInfo\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"\xc1\x01\n\x14\x43reatePackageRequest\x12\x16\n\x0eworkspace_path\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nbuild_type\x18\x03 \x01(\t\x12?\n\x07options\x18\x04 \x03(\x0b\x32..rqt2.api.v1.CreatePackageRequest.OptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x88\x02\n\x10WorkspaceService\x12V\n\rOpenWorkspace\x12!.rqt2.api.v1.OpenWorkspaceRequest\x1a\".rqt2.api.v1.OpenWorkspaceResponse\x12S\n\x0cListPackages\x12 .rqt2.api.v1.ListPackagesRequest\x1a!.rqt2.api.v1.ListPackagesResponse\x12G\n\rCreatePackage\x12!.rqt2.api.v1.CreatePackageRequest\x1a\x13.rqt2.api.v1.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workspace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPACKAGEREQUEST_OPTIONSENTRY']._loaded_options = None
  _globals['_CREATEPACKAGEREQUEST_OPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_OPENWORKSPACEREQUEST']._serialized_start=45
  _globals['_OPENWORKSPACEREQUEST']._serialized_end=81
  _globals['_PACKAGEINFO']._serialized_start=83
  _globals['_PACKAGEINFO']._serialized_end=144
  _globals['_OPENWORKSPACERESPONSE']._serialized_start=146
  _globals['_OPENWORKSPACERESPONSE']._serialized_end=250
  _globals['_LISTPACKAGESREQUEST']._serialized_start=252
  _globals['_LISTPACKAGESREQUEST']._serialized_end=297
  _globals['_LISTPACKAGESRESPONSE']._serialized_start=299
  _globals['_LISTPACKAGESRESPONSE']._serialized_end=402
  _globals['_CREATEPACKAGEREQUEST']._serialized_start=405
  _globals['_CREATEPACKAGEREQUEST']._serialized_end=598
  _globals['_CREATEPACKAGEREQUEST_OPTIONSENTRY']._serialized_start=552
  _globals['_CREATEPACKAGEREQUEST_OPTIONSENTRY']._serialized_end=598
  _globals['_WORKSPACESERVICE']._serialized_start=601
  _globals['_WORKSPACESERVICE']._serialized_end=865
# @@protoc_insertion_point(module_scope)
